apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: jenkins-integration
spec:
  selector:
    matchLabels:
      app: java
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: java
    spec:
      containers:
        - name: belajar-docker
          image: artdengun/Belajar-docker-Jenkins-Integrations
          ports:
            - containerPort: 80
