apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: java-jenkins
spec:
  selector:
    matchLabels:
      app: java
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: java
    spec:
      containers:
        - name: belajar-docker-jenkins-integrations
          image: artdengun/belajar-docker-jenkins-integration
          ports:
            - containerPort: 80
---
# https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service
kind: Service
apiVersion: v1
metadata:
  name: java-jenkins-service
spec:
  selector:
    app: java
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32000
  type: NodePort
